### ISSUE TITLE
[FEATURE] Array declaration (static array)

### ISSUE THREAD

**Issue by dhairyaj** [cimplec/sim-c#344] opened 2020-12-04 20:36 UTC
**Describe the solution you'd like**
Array declaration with or without assignment.

<strong>Syntax</strong>
Without assignment : 
var <array_name>[<size>]

<strong>Syntax</strong>
With assignment : 
array <array_name>[<size>] = {values separated by commas(,)}

**Comment by Math-O5** [comment] 2020-12-05 04:52
@dhairyaj May I be assigned? (Planning start only 15 December, but I'd like to do this).

**Comment by basilisk-2001** [comment] 2020-12-05 17:55
@dhairyaj  I'm ready to contribute . I can start from 6 December .

**Comment by frankhart2018** [comment] 2020-12-05 18:23
Sure assigning to both of you @Math-O5 @basilisk-2001.

**Comment by Math-O5** [comment] 2020-12-05 19:09
@basilisk-2001 Please, consider continue from [my branch in-344](https://github.com/Math-O5/sim-c/tree/in-344)

**Comment by basilisk-2001** [comment] 2020-12-07 08:31
@dhairyaj  @frankhart2018  The aim of this issue is still unclear to me . Can you please explain ? And I need to understand simC , suggest me some resource.

**Comment by Math-O5** [comment] 2020-12-07 12:02
@basilisk-2001 Read the section contributing in README [here](https://github.com/cimplec/sim-c/blob/master/README.md)

**Comment by frankhart2018** [comment] 2020-12-07 12:59
Thanks @Math-O5. @basilisk-2001 the issue is for declaration of an array. Take a look at variable declaration in simc_parser.py, things might seem clearer after that.

**Comment by basilisk-2001** [comment] 2020-12-07 16:46
@frankhart2018 @dhairyaj  I have created a pull request in my branch ...u can check it from fork ...can u plz confirm whether this is fine or not ?

**Comment by Math-O5** [comment] 2020-12-07 20:44
Hi @basilisk-2001, I suggest you first follow the tutorial I send above, it will help understand what is simc like. After that, it's needed read README.md to understand how simc works inside, then when start I recommend go to issues with tag "easy" first. This process no takes more than half day.

**Comment by Math-O5** [comment] 2020-12-07 20:51
@dhairyaj I've decided do it already since next questions depends on this, I think so.

**Comment by frankhart2018** [comment] 2020-12-08 07:50
Sure go ahead.

**Closed** 2020-12-08 19:08 UTC
Labels: KWoC'20, enhancement, moderate
