### ISSUE TITLE
simc fails to add reference address when input is not specified with data type

### ISSUE THREAD

**Issue by Chasmiccoder** [cimplec/sim-c#349] opened 2020-12-05 07:38 UTC
**Description of the Bug**
According to the documentation, if the test.simc file contains an input line like this:
var a = input( )
Then, the type selected will be string. However, during compilation, the test.c file does not accept the input successfully.

**To Reproduce the Bug**
1. In test.simc, write the line: **var a = input( )**
2. Run the simc compiler to create test.c
3. In test.c go over to the scanf( ) statement generated by the corresponding input( ) line of code.
4. See error. After compilation, the compiler uses **a** as an argument to scanf( ) instead of using **&a**.

**Expected behavior**
The compiler should add an & symbol before the variable.

**Screenshots**
According to the Documentation:
![image](https://user-images.githubusercontent.com/62545147/101236899-bb7a2400-36fa-11eb-8567-620842729109.png)

The .simc program statement:
![image](https://user-images.githubusercontent.com/62545147/101236839-63432200-36fa-11eb-8334-1e91127c8415.png)

After compilation (when .c file is created):
![image](https://user-images.githubusercontent.com/62545147/101236874-8968c200-36fa-11eb-886f-79cf6475db06.png)

This is why the program crashes whenever input( ) is used without specifying the data type.

**Desktop:**
 - OS: Windows 10, VS Code

**Comment by frankhart2018** [comment] 2020-12-05 15:17
Seems to be a duplicate of #183. Closing this.

**Closed by frankhart2018** 2020-12-05 15:17 UTC
Labels: bug
