### ISSUE TITLE
[BUG REPORT]When printing with variables embedded in strings all occurrences of the variable in the string are converted into format specifier

### ISSUE THREAD

**Issue by adenashameem** [cimplec/sim-c#149] opened 2020-10-02 15:35 UTC
**Describe the bug**
When using the syntax provided for printing with variables embedded in strings, each and every occurrence of that variable even in the string part is converted into a format specifier, however only the occurrence of the variable after the '=' sign should be converted into a format specifier.

**To Reproduce**
simC code:
MAIN 
    var a_var = 42
    print("The value of a_var = {a_var}")
END_MAIN

C code the above simC code generates right now:
#include <stdio.h>
int main() {
	int a_var = 42;
	printf("The value of %d = %d", a_var);

	return 0;
}
This C code gives the output:
The value of 42 = 10109280

**Expected behavior**
Expected C code:
#include <stdio.h>
int main() {
	int a_var = 42;
	printf("The value of a_var = %d", a_var);

	return 0;
}
Expected Output:
The value of a_var = 42

**Desktop:**
 - OS: [e.g. macOS]

**Comment by frankhart2018** [comment] 2020-10-02 15:36
Thanks @adenashameem for reporting the bug. Please also link this to #66 too. You can comment on that something like:-

Bug reported - When printing with variables embedded in strings all occurrences of the variable in the string are converted into format specifier #149.

**Comment by adenashameem** [comment] 2020-10-02 15:41
Can I try to fix this?

**Comment by frankhart2018** [comment] 2020-10-02 15:41
Sure @adenashameem, assigning this to you.

**Comment by Saptashrungi** [comment] 2020-12-06 17:16
I would like to work on this issue, some minor changes will be required, I will suggest a solution for this tomorrow.

**Comment by frankhart2018** [comment] 2020-12-07 07:33
Sure assigning this to you @Saptashrungi.

**Comment by Saptashrungi** [comment] 2020-12-07 16:15
I went through the code base, where mapping is done for variables in expression after `(`, to avoid the bug above we need to add one more `check if` to ensure, the mapping and replacement from `a_var` to `%d` occurs only if it is between {}.

**Comment by frankhart2018** [comment] 2020-12-07 17:22
@Saptashrungi ```check_if``` is used to check if types are similar or not, the issue is in how the replacement is made, it is done using python's inbuilt replace function which replaces all occurrences of the substring in the string with the format specifier, using an index based approach to replace might be helpful here I believe.

**Comment by Saptashrungi** [comment] 2020-12-07 17:31
Yes I went through the `expression` function, where in a for loop we are replacing based on `op_type` I guess, so we are parsing through the string, we will replace only if curly braces are encountered, we can use index approach.

**Comment by frankhart2018** [comment] 2020-12-07 17:32
Yeah :)

**Comment by Saptashrungi** [comment] 2020-12-08 07:45
I am facing a problem in debugging, even after commenting out or change a significant part of code in simc_parser.py , I get same opcode.

**Comment by frankhart2018** [comment] 2020-12-08 07:49
Can you join https://join.slack.com/t/sim-cnewdevs/shared_invite/zt-jgfthwau-V0INVtZQAaZ4RERZbE2lGg?

**Comment by Saptashrungi** [comment] 2020-12-08 07:52
Yes

**Comment by Math-O5** [comment] 2020-12-10 18:05
@frankhart2018 @Saptashrungi This issue should be closed?

**Comment by frankhart2018** [comment] 2020-12-10 18:05
Yeah this is merged.

**Closed** 2020-12-10 18:09 UTC
Labels: KWoC'20, bug, moderate

**Comment by Saptashrungi** [comment] 2020-12-10 18:17
> @frankhart2018 @Saptashrungi This issue should be closed?

Yes it's fixed.
