### ISSUE TITLE
[FEATURE] Array Assignment (static array)

### ISSUE THREAD

**Issue by dhairyaj** [cimplec/sim-c#345] opened 2020-12-04 20:38 UTC
**Describe the solution you'd like**
Array assignment for an already declared array.

<strong>Syntax</strong>
<array_name> = {values separated by commas(,)}

<strong>Example</strong>
```
var my_array[8]
my_array = {value, value, ..., value}
```

**Hint:** C does not support this initialization, you should translate the initialization in a for-loop or use pointers as suggested [stack possible-to-initialize-an-array-after-the-declaration-in-c]( https://stackoverflow.com/questions/8886375/possible-to-initialize-an-array-after-the-declaration-in-c)

**Comment by Math-O5** [comment] 2020-12-05 04:51
@dhairyaj May I be assigned? (Planning start only 15 December, but I'd like to do this).

**Comment by basilisk-2001** [comment] 2020-12-05 17:46
@dhairyaj   I'm ready to do this thing . I can start from 6 December

**Comment by frankhart2018** [comment] 2020-12-05 18:24
Sure assigning this to both of you @Math-O5 @basilisk-2001

**Comment by 4shw4n1** [comment] 2020-12-06 08:38
@dhairyaj  I think I can fix this issue. Could you please assign this to me also?

**Comment by frankhart2018** [comment] 2020-12-06 09:13
Sure assigning this to you too @4shw4n1.

**Comment by Math-O5** [comment] 2020-12-07 16:18
@dhairyaj Is it not a duplicate of #344 ? If not, what are the difference?

**Comment by basilisk-2001** [comment] 2020-12-07 16:45
@frankhart2018 @dhairyaj  I have created a pull request in my branch ...u can check it from fork ...can u plz confirm whether this is fine or not ?

**Comment by frankhart2018** [comment] 2020-12-07 17:23
I added some comments in your PR @basilisk-2001.

**Comment by Math-O5** [comment] 2020-12-07 23:56
@dhairyaj I think you should put the code in C to facilitate the understand.

**Comment by Math-O5** [comment] 2020-12-08 00:04
@dhairyaj I will let it with @4shw4n1  and @basilisk-2001. but, anyway, what is the code C expected to be generated?

**Comment by frankhart2018** [comment] 2020-12-08 07:58
Check this @Math-O5 https://stackoverflow.com/questions/8886375/possible-to-initialize-an-array-after-the-declaration-in-c. I guess if assignment is done after declaration it has to be a pointer.

**Comment by shobhit10058** [comment] 2020-12-10 17:42
is this issue resolved? Other array issues depends on the array declaration issue which I want to try? So if this issue is available I can try from this issue.

**Comment by Math-O5** [comment] 2020-12-10 17:50
@shobhit10058 No, the issue is open. But note, the array declaration already exist, it's now `var name[30]` and genetic `var <name>[<in>|<void>]`. The issue is about assign after created array: https://stackoverflow.com/questions/8886375/possible-to-initialize-an-array-after-the-declaration-in-c

**Comment by Math-O5** [comment] 2020-12-10 18:09
@Shaheer-rossoneri14 Thanks for showing interest in contributing!

**Comment by shobhit10058** [comment] 2020-12-10 18:27
oh then its fine!!!

**Closed** 2021-01-07 11:47 UTC
Labels: SWoC 2021, easy, enhancement, high priority
